image: Ubuntu1804 # образ для сборки
stack: node 10 # окружение
# ветка git
branches:
  only:
    - master
# кеширование
cache: node_modules
# установка зависимостей
install:
  - npm install
build: off
# сборка
build_script:
  - npm run build
# скрипт тестирования
test_script:
  - npm run lint
deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose